name = "solana-bridge"
compatibility_date = "2026-06-11"

[assets]
directory = "./build"
not_found_handling = "single-page-application"

[[routes]]
pattern = "bridge-solana.weatherxm.network"
custom_domain = true
